apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: recrutment-task-mbekas
  region: us-west-1
  version: "1.22"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
